version: "3"
services:
  db:
    image: mariadb:10.5.8
    restart: always
    env_file:
      - .env
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "3000:80"
    env_file:
      - .env
    volumes:
      ["./web:/var/www/html"]
volumes:
  mysql: {}
